{
 "title": "Greenhouse",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "lights", "label": "Lights", "query": "SHOW MEASUREMENTS" },
   { "name": "temps", "label": "Temps", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "gh_humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$lights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "repeat": "lights",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$lights$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$lights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$lights$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$lights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$lights$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$lights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$lights$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "repeat": "temps",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  },
  {
   "title": "$temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenhouse" }
     ]
    }
   ]
  }
 ]
}