{
 "title": "Server-Room",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "cpus", "label": "CPUS", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "sr_power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "sr_noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "sr_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "sr_memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "$cpus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "repeat": "cpus",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cpus$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "$cpus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cpus$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "$cpus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cpus$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  },
  {
   "title": "$cpus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$cpus$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server-room" }
     ]
    }
   ]
  }
 ]
}