{
 "title": "Wellness",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "water_temps", "label": "WATER_TEMPS", "query": "SHOW MEASUREMENTS" },
   { "name": "sauna_temps", "label": "SAUNA_TEMPS", "query": "SHOW MEASUREMENTS" },
   { "name": "sauna_humidity", "label": "SAUNA_HUMIDITY", "query": "SHOW MEASUREMENTS" }
  ]
 },
 "panels": [
  {
   "title": "Sportbecken Temp",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "wn_temp_water0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Salzwasserbecken Temp",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "wn_temp_water1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Solebecken Temp",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "wn_temp_water2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Ruhebereich Lautstärke",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "wn_noise",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Finnische Sauna Temp",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "repeat": "sauna_temps",
   "targets": [
    {
     "measurement": "/^$sauna_temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Finnische Sauna Temp",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "measurement": "/^$sauna_temps$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Finnische Sauna Feuchtigkeit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "repeat": "sauna_humidity",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$sauna_humidity$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  },
  {
   "title": "Finnische Sauna Feuchtigkeit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "/^$sauna_humidity$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wellness" }
     ]
    }
   ]
  }
 ]
}